# Generate embedded.h: turn payload_web files into C++ byte arrays for Setup.cpp.
# Usage: gen_embedded.ps1 <payloadDir> <outHeader>
# NOTE: keep this script ASCII-only (Windows PowerShell 5.1 reads .ps1 as ANSI
#       without BOM, so UTF-8 Chinese literals would be mis-decoded).
param(
    [Parameter(Mandatory=$true)][string]$PayloadDir,
    [Parameter(Mandatory=$true)][string]$OutFile
)

$ErrorActionPreference = "Stop"

# Collect payload files in a deterministic order (app exe/config first, then dlls).
$all = Get-ChildItem -LiteralPath $PayloadDir -File
$ordered = @()

# 1) main program exe (not Uninstall / Setup)
foreach ($f in $all) {
    if ($f.Extension -eq '.exe' -and $f.Name -notlike 'Uninstall*' -and $f.Name -notlike '*Setup*') {
        $ordered += $f
    }
}
# 2) its .config
foreach ($f in $all) {
    if ($f.Extension -eq '.config') { $ordered += $f }
}
# 3) WebView2 dlls in fixed order
foreach ($dllName in @('Microsoft.Web.WebView2.Core.dll','Microsoft.Web.WebView2.WinForms.dll','WebView2Loader.dll')) {
    foreach ($f in $all) {
        if ($f.Name -eq $dllName) { $ordered += $f }
    }
}

if ($ordered.Count -eq 0) { throw "no payload files found in $PayloadDir" }

# Convert a .NET string to a C++ wide-string literal using \uXXXX escapes.
function To-WideLiteral {
    param([string]$s)
    $out = New-Object System.Text.StringBuilder
    foreach ($ch in $s.ToCharArray()) {
        $hex = '{0:X4}' -f [int]$ch
        $null = $out.Append('\u' + $hex)
    }
    return $out.ToString()
}

$sb = New-Object System.Text.StringBuilder
$null = $sb.AppendLine("// auto-generated by gen_embedded.ps1, do not edit.")
$null = $sb.AppendLine("#pragma once")
$null = $sb.AppendLine("")

$entry = @()
for ($i = 0; $i -lt $ordered.Count; $i++) {
    $bytes = [System.IO.File]::ReadAllBytes($ordered[$i].FullName)
    $null = $sb.AppendLine("static const unsigned char kFile$i[] = {")
    $line = New-Object System.Text.StringBuilder
    for ($j = 0; $j -lt $bytes.Length; $j++) {
        $h = '0x{0:X2},' -f $bytes[$j]
        $null = $line.Append($h)
        if (($j + 1) % 16 -eq 0) {
            $null = $sb.AppendLine("    " + $line.ToString())
            $line = New-Object System.Text.StringBuilder
        }
    }
    if ($line.Length -gt 0) { $null = $sb.AppendLine("    " + $line.ToString()) }
    $null = $sb.AppendLine("};")
    $null = $sb.AppendLine("")

    $wl = To-WideLiteral $ordered[$i].Name
    $entry += "    { L`"$wl`", kFile$i, sizeof(kFile$i) }"
}

$null = $sb.AppendLine("struct EmbeddedFile {")
$null = $sb.AppendLine("    const wchar_t* name;")
$null = $sb.AppendLine("    const unsigned char* data;")
$null = $sb.AppendLine("    unsigned long size;")
$null = $sb.AppendLine("};")
$null = $sb.AppendLine("")
$null = $sb.AppendLine("static const EmbeddedFile kPayload[] = {")
foreach ($e in $entry) { $null = $sb.AppendLine($e + ",") }
$null = $sb.AppendLine("};")
$null = $sb.AppendLine("static const unsigned long kPayloadCount = $($ordered.Count);")

[System.IO.File]::WriteAllText($OutFile, $sb.ToString(), (New-Object System.Text.UTF8Encoding($false)))
Write-Output "generated $OutFile  ($($ordered.Count) files)"
